_core:
  default_config_hash: RGedRkFydKZjS0ZJ6vbtZH00KbhYVGsK-ABILHdQLyw
prompt_logging: false
prompt_logging_tags: ''
default_providers:
  chat:
    provider_id: groq
    model_id: llama-3.3-70b-versatile
  embeddings:
    provider_id: ollama
    model_id: llama3_2_latest
default_vdb_provider: pinecone
